### PR TITLE
Add Scala 2.13 support

### LINKED ISSUE #29: Add 2.13 build/CI
ZIO now support Scala 2.13, so this library should too.

### PR DESCRIPTION
**Pull request by solicode**
Closes #29

Disables the tests for 2.13 temporary until elasticmq supports it.

Also, I saw a reference to Scala 2.11 in `build.sbt`, but it doesn't seem to actually be used (and I don't see 2.11 published), so I'm assuming that was just remnants from an old build file and it wasn't intentional.

### CODE REVIEW

**Comment by solicode** [comment]
Ah, just saw config.yaml. That will also have to be updated.

**Comment by solicode** [comment]
Finally... 😅

Also, apparently there's no `hseeberger/scala-sbt:8u213_*`. Not sure what you want to do about that. I just removed it.

**Comment by ghostdogpr** [comment]
Looks good! I see there are a few deprecation warnings in 2.13, could you have a look?

**Comment by solicode** [comment]
Yeah, those JavaConverters warnings come up a lot when upgrading to 2.13. I've seen many different ways of handling it. Some people just ignore them (or use the silencer plugin), while others do tedious code splitting. There's also [this](https://github.com/scala/scala-collection-compat/issues/208#issuecomment-497735669). And then there's `scala-collection-compat`. That's the one I went with. Not sure which you prefer though.

**Comment by ghostdogpr** [comment]
All good, thanks! I’ll do a release.

**Pull request merged**
